In [1]:
import pandas as pd

signals = pd.read_csv(
    "D:/operational-signal-intelligence-environment/outputs/signal_intelligence_table.csv"
)

signals.head()

,timestamp,signal_name,severity,reason,supporting_metric,confidence
0,2025-01-02 15:30:00,Demand Spike,High,Demand exceeded spike threshold,38264.0,High
1,2025-01-02 16:00:00,Demand Spike,High,Demand exceeded spike threshold,39309.0,High
2,2025-01-02 16:30:00,Demand Spike,High,Demand exceeded spike threshold,40412.0,High
3,2025-01-02 17:00:00,Demand Spike,High,Demand exceeded spike threshold,41103.0,High
4,2025-01-02 17:30:00,Demand Spike,High,Demand exceeded spike threshold,41589.0,High

In [2]:
signal_metadata = {

    "Demand Spike": {
        "impact_area": "Grid Demand",
        "owner": "Regional Controller",
        "resolution_target": "2 Hours",
        "operational_consequence":
        "Potential grid stress due to elevated demand"
    },

    "Forecast Failure": {
        "impact_area": "Forecasting",
        "owner": "Forecast Analyst",
        "resolution_target": "4 Hours",
        "operational_consequence":
        "Reduced forecasting reliability"
    },

    "Low Renewable Window": {
        "impact_area": "Sustainability",
        "owner": "Energy Operations Team",
        "resolution_target": "6 Hours",
        "operational_consequence":
        "Increased dependence on fossil generation"
    },

    "High Carbon Period": {
        "impact_area": "Carbon Management",
        "owner": "Sustainability Manager",
        "resolution_target": "4 Hours",
        "operational_consequence":
        "Elevated carbon emissions"
    },

    "Supply Stress": {
        "impact_area": "Grid Capacity",
        "owner": "Regional Controller",
        "resolution_target": "1 Hour",
        "operational_consequence":
        "Potential supply shortfall"
    },

    "Generation Surplus": {
        "impact_area": "Generation Management",
        "owner": "Operations Team",
        "resolution_target": "6 Hours",
        "operational_consequence":
        "Excess generation capacity available"
    },

    "Renewable Surge": {
        "impact_area": "Renewable Operations",
        "owner": "Renewable Operations Team",
        "resolution_target": "4 Hours",
        "operational_consequence":
        "Exceptional renewable contribution"
    },

    "Demand Drop": {
        "impact_area": "Demand Management",
        "owner": "Operations Team",
        "resolution_target": "4 Hours",
        "operational_consequence":
        "Demand significantly below expected levels"
    }

}

In [3]:
signals["impact_area"] = signals["signal_name"].apply(
    lambda x: signal_metadata[x]["impact_area"]
)

signals["owner"] = signals["signal_name"].apply(
    lambda x: signal_metadata[x]["owner"]
)

signals["resolution_target"] = signals["signal_name"].apply(
    lambda x: signal_metadata[x]["resolution_target"]
)

signals["operational_consequence"] = signals["signal_name"].apply(
    lambda x: signal_metadata[x]["operational_consequence"]
)

In [8]:
signals.shape

(20909, 10)

In [4]:
signals.head()

,timestamp,signal_name,severity,reason,supporting_metric,confidence,impact_area,owner,resolution_target,operational_consequence
0,2025-01-02 15:30:00,Demand Spike,High,Demand exceeded spike threshold,38264.0,High,Grid Demand,Regional Controller,2 Hours,Potential grid stress due to elevated demand
1,2025-01-02 16:00:00,Demand Spike,High,Demand exceeded spike threshold,39309.0,High,Grid Demand,Regional Controller,2 Hours,Potential grid stress due to elevated demand
2,2025-01-02 16:30:00,Demand Spike,High,Demand exceeded spike threshold,40412.0,High,Grid Demand,Regional Controller,2 Hours,Potential grid stress due to elevated demand
3,2025-01-02 17:00:00,Demand Spike,High,Demand exceeded spike threshold,41103.0,High,Grid Demand,Regional Controller,2 Hours,Potential grid stress due to elevated demand
4,2025-01-02 17:30:00,Demand Spike,High,Demand exceeded spike threshold,41589.0,High,Grid Demand,Regional Controller,2 Hours,Potential grid stress due to elevated demand

In [5]:
signals.to_csv(
    "D:/operational-signal-intelligence-environment/outputs/signal_priority_table.csv",
    index=False
)

print("Signal priority table generated successfully")

Signal priority table generated successfully