In [1]:
import pandas as pd

incident_df = pd.read_csv(
    "D:/operational-signal-intelligence-environment/outputs/incident_table.csv"
)

incident_df.head()

,incident_id,timestamp,incident_type,contributing_signals,severity,business_impact,recommended_response,escalation_path
0,INC-00001,2025-01-01 00:00:00,CURTAILMENT_RISK_INCIDENT,"Renewable Surge, Generation Surplus",Medium,Potential renewable curtailment,Evaluate renewable curtailment actions,Operator → Supervisor
1,INC-00002,2025-01-01 00:30:00,CURTAILMENT_RISK_INCIDENT,"Renewable Surge, Generation Surplus",Medium,Potential renewable curtailment,Evaluate renewable curtailment actions,Operator → Supervisor
2,INC-00003,2025-01-01 01:00:00,CURTAILMENT_RISK_INCIDENT,"Renewable Surge, Generation Surplus",Medium,Potential renewable curtailment,Evaluate renewable curtailment actions,Operator → Supervisor
3,INC-00004,2025-01-01 01:30:00,CURTAILMENT_RISK_INCIDENT,"Renewable Surge, Generation Surplus",Medium,Potential renewable curtailment,Evaluate renewable curtailment actions,Operator → Supervisor
4,INC-00005,2025-01-01 02:00:00,CURTAILMENT_RISK_INCIDENT,"Renewable Surge, Generation Surplus",Medium,Potential renewable curtailment,Evaluate renewable curtailment actions,Operator → Supervisor

In [2]:
def assign_escalation(severity):

    if severity == "Critical":
        return "Executive"

    elif severity == "High":
        return "Regional Controller"

    elif severity == "Medium":
        return "Supervisor"

    else:
        return "Operator"

In [3]:
incident_df["owner"] = (
    incident_df["severity"]
    .apply(assign_escalation)
)

In [4]:
def notification_group(owner):

    mapping = {

        "Operator":
            "Operations Team",

        "Supervisor":
            "Operations Supervisor",

        "Regional Controller":
            "Regional Leadership",

        "Executive":
            "Executive Leadership"

    }

    return mapping[owner]

In [5]:
incident_df["notification_group"] = (
    incident_df["owner"]
    .apply(notification_group)
)

In [6]:
def escalation_path(owner):

    paths = {

        "Operator":
            "Operator",

        "Supervisor":
            "Operator → Supervisor",

        "Regional Controller":
            "Operator → Supervisor → Regional Controller",

        "Executive":
            "Operator → Supervisor → Regional Controller → Executive"

    }

    return paths[owner]

In [7]:
incident_df["escalation_path"] = (
    incident_df["owner"]
    .apply(escalation_path)
)

In [8]:
escalation_queue = incident_df[
    [
        "incident_id",
        "timestamp",
        "incident_type",
        "severity",
        "owner",
        "notification_group",
        "escalation_path"
    ]
]

In [9]:
escalation_queue.head()

,incident_id,timestamp,incident_type,severity,owner,notification_group,escalation_path
0,INC-00001,2025-01-01 00:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
1,INC-00002,2025-01-01 00:30:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
2,INC-00003,2025-01-01 01:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
3,INC-00004,2025-01-01 01:30:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
4,INC-00005,2025-01-01 02:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor

In [10]:
escalation_queue.to_csv(
    "D:/operational-signal-intelligence-environment/outputs/escalation_queue.csv",
    index=False
)

print("Escalation queue generated successfully")

Escalation queue generated successfully

In [11]:
escalation_queue.shape

(5526, 7)

In [12]:
escalation_queue["owner"].value_counts()

owner
Supervisor             3261
Operator               1610
Regional Controller     578
Executive                77
Name: count, dtype: int64

In [13]:
escalation_queue.head()

,incident_id,timestamp,incident_type,severity,owner,notification_group,escalation_path
0,INC-00001,2025-01-01 00:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
1,INC-00002,2025-01-01 00:30:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
2,INC-00003,2025-01-01 01:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
3,INC-00004,2025-01-01 01:30:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor
4,INC-00005,2025-01-01 02:00:00,CURTAILMENT_RISK_INCIDENT,Medium,Supervisor,Operations Supervisor,Operator → Supervisor